In [55]:
import json

import pandas as pd
import numpy as np

from contextlib import suppress
import os

In [56]:
stats_path = "results"
hb_stats = None
full_stats = None

with suppress(FileNotFoundError):
    with open(os.path.join(stats_path, "results_hb.json")) as f:
        hb_stats =  json.load(f)
with suppress(FileNotFoundError):
    with open(os.path.join(stats_path, "results_full.json")) as f:
        full_stats = json.load(f)

# for f in os.scandir("results")  :
#     if f.is_dir():
#         print(f.name)
        # for f_in in os.scandir(f.path):
        #     print(f_in)

## Best reconstruction models

### For heartbeat experiments

In [67]:
df_hb = None
if hb_stats is not None:
    df_hb = pd.DataFrame.from_dict(hb_stats)
    df_hb.sort_values(by=["mse"], ascending=True, inplace=True)
df_hb[['name', 'mae', 'snr', 'latent_mean', 'latent_std', 'silhouette', 'davies_bouldin','active_dims']].head(5)

,name,mae,snr,latent_mean,latent_std,silhouette,davies_bouldin,active_dims
15,TRANSFORMER-no-reg_Best,0.003312,33.221412,0.130209,0.080511,0.0293,2.4867,3
14,TRANSFORMER-no-reg,0.003550,33.194845,0.130110,0.075097,0.0320,2.4007,1
8,TRANSFORMER-baseline,0.004333,30.808263,-0.186962,0.054138,0.0406,2.2773,0
9,TRANSFORMER-baseline_Best,0.004393,30.772204,-0.184310,0.055746,0.0416,2.3036,0
13,TRANSFORMER-big-boy_Best,0.004070,29.195607,-0.208060,0.302179,0.0787,1.8807,128

### For full ECG signal experiments

In [62]:
df_full = None
if full_stats is not None:
    df = pd.DataFrame.from_dict(full_stats)
    df.sort_values(by=["mse"], ascending=True, inplace=True)
df_full

## Best clustering models

- validated with Kmeans clustering at first(baseline)

In [65]:
df_hb = None
if hb_stats is not None:
    df_hb = pd.DataFrame.from_dict(hb_stats)
    df_hb.sort_values(by=["silhouette"], ascending=False, inplace=True)
df_hb[['name', 'mae', 'snr', 'latent_mean', 'latent_std', 'silhouette', 'davies_bouldin','active_dims']].head(5)

,name,mae,snr,latent_mean,latent_std,silhouette,davies_bouldin,active_dims
22,LSTM-VAE-big-model,0.034449,12.132957,-0.004670,1.559444,0.3462,2.4182,128
23,LSTM-VAE-big-model_Best,0.035088,11.958687,-0.003237,1.628719,0.3443,2.2596,128
12,TRANSFORMER-big-boy,0.004401,28.950150,-0.228985,0.346225,0.1024,1.7496,128
13,TRANSFORMER-big-boy_Best,0.004070,29.195607,-0.208060,0.302179,0.0787,1.8807,128
4,CNN-deep,0.060761,7.313734,1.143130,19.584389,0.0566,2.3121,64

In [60]:
if full_stats is not None:
    df = pd.DataFrame.from_dict(full_stats)
    df.sort_values(by=["mse"], ascending=True, inplace=True)